# Generated by Django 6.0.6 on 2026-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_settled',
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('UNEQUAL', 'Unequal'), ('PERCENT', 'Percentage'), ('SHARES', 'Shares')], default='EQUAL', max_length=20),
        ),
    ]
