# Generated by Django 6.0.6 on 2026-06-15 03:13

from django.db import migrations


def seed_default_currencies(apps, schema_editor):
    Currency = apps.get_model("expenses", "Currency")

    Currency.objects.update_or_create(
        code="INR",
        defaults={"name": "Indian Rupee", "symbol": "₹", "is_active": True},
    )
    Currency.objects.update_or_create(
        code="USD",
        defaults={"name": "US Dollar", "symbol": "$", "is_active": True},
    )


def unseed_default_currencies(apps, schema_editor):
    Currency = apps.get_model("expenses", "Currency")
    Currency.objects.filter(code__in=["INR", "USD"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expensesplit_owed_amount_inr_exchangerate"),
    ]

    operations = [
        migrations.RunPython(seed_default_currencies, unseed_default_currencies),
    ]
