# Generated by Django 6.0.6 on 2026-06-15 03:21

from datetime import date
from decimal import Decimal

from django.db import migrations


def seed_usd_inr_rate(apps, schema_editor):
    Currency = apps.get_model("expenses", "Currency")
    ExchangeRate = apps.get_model("expenses", "ExchangeRate")

    usd = Currency.objects.get(code="USD")
    inr = Currency.objects.get(code="INR")

    ExchangeRate.objects.update_or_create(
        from_currency=usd,
        to_currency=inr,
        effective_date=date(2026, 6, 15),
        defaults={"rate": Decimal("95.14")},
    )


def unseed_usd_inr_rate(apps, schema_editor):
    ExchangeRate = apps.get_model("expenses", "ExchangeRate")
    ExchangeRate.objects.filter(
        from_currency__code="USD",
        to_currency__code="INR",
        effective_date=date(2026, 6, 15),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_seed_default_currencies"),
    ]

    operations = [
        migrations.RunPython(seed_usd_inr_rate, unseed_usd_inr_rate),
    ]
