# Generated by Django 6.0.6 on 2026-06-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="groupmembership",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE groups_groupmembership "
                        "ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT TRUE"
                    ),
                    reverse_sql=(
                        "ALTER TABLE groups_groupmembership "
                        "DROP COLUMN IF EXISTS is_active"
                    ),
                )
            ],
        ),
    ]
